server:
  port: 8090

spring:
  application:
    name: personal
  datasource:
      username: 'postgres'
      url: jdbc:postgresql://localhost:5431/postgres
      password: 'postgres'
      driver-class-name: org.postgresql.Driver
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: 'true'


  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    ratelimiters:
      enabled: true

resilience4j:
  ratelimiter:
    instances:
      personal-limiter:
        limit-for-period: 5
        limit-refresh-period: 15s
        timeout-duration: 10s
        register-health-indicator: true